# Generated by Django 4.1.5 on 2023-01-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='acct_mang_dbrn_code',
            field=models.CharField(max_length=16, verbose_name='ACCT_MANG_DBRN_CODE'),
        ),
    ]
